# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=128, verbose_name='Short url')),
                ('original_url', models.URLField(max_length=512, verbose_name='Original url')),
                ('created_dt', models.DateTimeField(auto_now=True, verbose_name='Created Date')),
                ('redirect_count', models.PositiveIntegerField(default=0, verbose_name='Redirect count')),
            ],
            options={
                'verbose_name': 'Moder converted url',
            },
        ),
    ]
